## Python Fundamentals

### 1. Reading & Writing CSV Files

Change the directory to data file folder.

In [14]:
%cd D:\Data Science\GitHub\Python Learning\Python-for-Data-Science\Data Files\Python Learning

D:\Data Science\GitHub\Python Learning\Python-for-Data-Science\Data Files\Python Learning


Import the file as a **list of dictionaries**.

In [34]:
import csv

%precision 2

with open('expense_report.csv') as dat0:
    pay_dat = list(csv.DictReader(dat0))
    
    
pay_dat[:3]

[OrderedDict([('TRXN_MONTH', 'Mar-19'),
              ('TRXN_DT', '01/03/2019'),
              ('TRXN_AMT', '61.2'),
              ('MERCHT_NAME', 'VIRGIN ACTIVE'),
              ('CATG', 'Entertainment')]),
 OrderedDict([('TRXN_MONTH', 'Mar-19'),
              ('TRXN_DT', '04/03/2019'),
              ('TRXN_AMT', '1.31'),
              ('MERCHT_NAME', 'LOON FUNG LIMITED'),
              ('CATG', 'Glossary')]),
 OrderedDict([('TRXN_MONTH', 'Mar-19'),
              ('TRXN_DT', '04/03/2019'),
              ('TRXN_AMT', '16.89'),
              ('MERCHT_NAME', 'LOON FUNG LIMITED'),
              ('CATG', 'Glossary')])]

In [35]:
# Check length of the dictionary.
len(pay_dat)

1207

Return the keys of first element in <i>pay_dat</i>.

In [36]:
pay_dat[0].keys()

odict_keys(['TRXN_MONTH', 'TRXN_DT', 'TRXN_AMT', 'MERCHT_NAME', 'CATG'])

Calculate the <b>average transaction</b> amount in the spreadsheet.

In [37]:
sum(float(i['TRXN_AMT']) for i in pay_dat)/len(pay_dat)

34.08

Create a <b>set</b> of categories.

In [38]:
exp_cat = set(i['CATG'] for i in pay_dat)
exp_cat

{'Business Expense',
 'Cash Out',
 'Eating Out',
 'Electronic Product',
 'Entertainment',
 'Filght Ticket',
 'Finance',
 'Furniture',
 'Glossary',
 'Gym & Sports',
 "Jinlei's Credit Card",
 'Online Course Learning',
 'Other',
 'Property',
 'RMB (Milk Powder)',
 'Rent',
 'Shopping',
 'Transport',
 'Utility Bill'}

Calculate <b>average transaction amount</b> for each expense cateogy.

In [47]:
Ave_TrxnAmt_Cat = []

for cat in exp_cat:
    exp_sum = 0
    exp_count = 0
    
    for exp_amt in pay_dat:
        if exp_amt['CATG'] == cat:
            exp_sum += float(exp_amt['TRXN_AMT'])
            exp_count += 1
    Ave_TrxnAmt_Cat.append((cat,exp_sum/exp_count))

Sort the output list by <b><i>lengh of Category Name</i></b>.
<br>
Here we need to use <i>.sort(key = ..)</i>.

In [60]:
Ave_TrxnAmt_Cat.sort(key = lambda x: len(x[0]))
Ave_TrxnAmt_Cat

[('Rent', 447.00),
 ('Other', 14.09),
 ('Finance', 100.00),
 ('Glossary', 9.70),
 ('Property', 519.74),
 ('Shopping', 98.73),
 ('Cash Out', 45.00),
 ('Furniture', 268.67),
 ('Transport', 8.76),
 ('Eating Out', 12.07),
 ('Utility Bill', 96.47),
 ('Gym & Sports', 34.29),
 ('Entertainment', 38.08),
 ('Filght Ticket', 745.00),
 ('Business Expense', 57.76),
 ('RMB (Milk Powder)', 172.00),
 ('Electronic Product', 249.00),
 ("Jinlei's Credit Card", 1075.00),
 ('Online Course Learning', 30.00)]

### 2. Python Dates and Times

Frequently used packages in Python for dates & time manipulations.

In [61]:
import datetime as dt
import time as tm

Check the time stamp of current moment.

In [62]:
tm.time()

1581247515.23

Extract year, month, date etc from the timestamp.

In [65]:
dtnow = dt.datetime.fromtimestamp(tm.time())
dtnow

datetime.datetime(2020, 2, 9, 11, 28, 25, 219905)

In [66]:
type(dtnow)

datetime.datetime

In [70]:
delta = dt.timedelta(days = 100)
type(delta)

datetime.timedelta

In [71]:
today = dt.date.today()

In [73]:
today > today - delta

True

### 3. Advanced Python Objects, map()

An example of class.

In [74]:
class Person:
    department = 'School of Information'
    
    def set_name(self, new_names):
        self.name = new_names
    def set_location(self, new_location):
        self.location = new_location


* <b>map()</b> function

In [80]:
store1 = [10.00, 11.00, 90.43, 2.83]
store2 = [16.00, 12.00, 63.33, 1.38]
cheapest = map(min, store1, store2)
cheapest

It does not return the <b>acutal output</b> of the calculation.

In [81]:
for i in cheapest:
    print(i)

10.0
11.0
63.33
1.38


An example to apply <b>map()</b> function:

In [96]:
people = ['Dr. Christopher Brooks', 
          'Dr. Kevyn Collins-Thompson', 
          'Dr. VG Vinod Vydiswaran', 
          'Dr. Daniel Romero']

def split_title_surname (person):
    return person.split(' ')[0] + person.split(' ')[-1]

list(map(split_title_surname, people))

['Dr.Brooks', 'Dr.Collins-Thompson', 'Dr.Vydiswaran', 'Dr.Romero']

### 4. Advanced Python Lambda and List Comprehensions

* <b>Lambda</b> example:

In [99]:
my_function = lambda a, b, c: a + b + c
my_function(1,2,3)

6

* <b>List Comprehension</b> example:

<u>Commen method</u> to print list of even numbers

In [103]:
my_list = []
for number in range(0,10):
    if number % 2 == 0:
        my_list.append(number)
my_list

[0, 2, 4, 6, 8]

<br>Return the same result by <u>list comprehension</u>

In [105]:
my_list = [number for number in range(0,10) if number % 2 ==0]
my_list

[0, 2, 4, 6, 8]

### 5. Numpy

Import the package.

In [111]:
import numpy as np

#### Creating Arrays

In [115]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])
m = np.array([[7, 8, 9],[10, 11, 12]])
m

array([[ 7,  8,  9],
       [10, 11, 12]])

Check the dimension of an array.

In [117]:
m.shape

(2, 3)

Create a equally spaced 1-dimensional array.

In [125]:
n = np.arange(0, 30, 2)
n

numpy.ndarray

Reshape the 1-dimenional array to be 3-by-5 array.


In [129]:
n = n.reshape(3, 5)
n

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28]])

Create a 1-dimensional array by defining number of elements.

In [138]:
m = np.linspace(0, 4, 9)
m = m.resize(3, 3)
m

* <b>Some useful functions</b>

In [140]:
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [141]:
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [142]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [143]:
np.diag([1,2,3,4])

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])